### ISSUE TITLE
Travis CI currently builds the app but does not run it

### ISSUE THREAD

**Issue by cclauss** [rootm0s/WinPwnage#25]
Perhaps it would be a good idea to add a command to the end of the __.travis.yml__ file that ___runs___ the app.
* Does it run as expected in Python 2?
* Does it run as expected in Python 3?

**Comment by cclauss** [comment]
After the __python build.py__ runs successuflly, shouldn't there be a __.exe__ file created?
If so, what should it be called and where should it be located?

**Comment by rootm0s** [comment]
If we build an executable, the binary is saved inside `currentDir\dist` as `winpwnage.exe`

**Comment by cclauss** [comment]
$ __python3 build.py winpwnage.py__
```
running py2exe
The command "python build.py winpwnage.py" exited with 1.
Traceback (most recent call last):
  File "build.py", line 22, in <module>
    setup(console=[args], options=opts, zipfile=None)
  File "C:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Python37\lib\site-packages\py2exe\runtime.py", line 158, in analyze
    self.mf.import_package(modname[:-2])
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 92, in import_package
    self.import_hook(name)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range
ls: cannot access 'dist': No such file or directory
```
