### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kalimon12** [rootm0s/WinPwnage#47]
Traceback (most recent call last):
  File "winpwnage.py", line 4, in <module>
    from winpwnage.core.scanner import scanner, function
  File "/home/xubuntu/tools/WinPwnage/winpwnage/core/scanner.py", line 1, in <module>
    from winpwnage.functions.uac.uac_runas import *
  File "/home/xubuntu/tools/WinPwnage/winpwnage/functions/uac/uac_runas.py", line 2, in <module>
    from winpwnage.core.utils import *
  File "/home/xubuntu/tools/WinPwnage/winpwnage/core/utils.py", line 7, in <module>
    import winreg as _winreg
  File "/usr/local/lib/python2.7/dist-packages/winreg/__init__.py", line 6, in <module>
    from _winreg import *
ImportError: No module named _winreg

**Comment by rootm0s** [comment]
You are running on linux lol. This is a Windows package.
